[libdefaults]
        dns_canonicalize_hostname = false
        default_realm = {{ KRB_REALM }}
        dns_lookup_realm = false
        dns_lookup_kdc = false
        ticket_lifetime = 24h
        forwardable = true
        proxiable = true
        rdns = false

[realms]
        {{ KRB_REALM }} = {
                kdc = {{ DOMAIN_NAME }}
                admin_server = {{ DOMAIN_NAME }}
                default_domain = {{ DOMAIN_NAME }}
        }
